name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Giả sử biến này được khai báo ở nơi khác
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # Giả sử biến này được khai báo ở nơi khác
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Google Cloud authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id:  ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/$GCP_PROJECT_ID/mywebapp:$GITHUB_SHA src/MyWebApp/
        docker push gcr.io/$GCP_PROJECT_ID/mywebapp:$GITHUB_SHA

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Set up GCloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id:  ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/mywebapp-deployment mywebapp=gcr.io/$GCP_PROJECT_ID/mywebapp:$GITHUB_SHA
